### ISSUE TITLE
Validación de propuesta de valor

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-pc-box#2]
[Practica 1 VALIDACION DE PROPUESTA DE VALOR.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-pc-box/files/6118720/Practica.1.VALIDACION.DE.PROPUESTA.DE.VALOR.pdf)

**Comment by Edwin-1012** [comment]
20 puntos, ha nuestro criterio mantuvieron todos los puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
