### ISSUE TITLE
PRACTICA DE COSTOS

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-pc-box#3]
[Practica de costos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-pc-box/files/6135363/Practica.de.costos.pdf)

**Comment by Edwin-1012** [comment]
20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
